title: Parker-Damon Parent Information Hub
description: An unofficial, parent-maintained information resource for the Parker-Damon school community.
url: "https://eamacm.github.io"
baseurl: "/unofficial_parker_damon_info_hub"
timezone: America/New_York
permalink: /updates/:year/:month/:day/:title/
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
